In [58]:
import pandas as pd
import numpy as np

In [59]:
fertilizer_data=pd.read_csv('FertilizerPrediction.csv')

In [60]:
fertilizer_data.head()

Temparature  Humidity   Moisture Soil Type  Crop Type  Nitrogen  Potassium   
0           26         52        38     Sandy      Maize        37          0  \
1           29         52        45     Loamy  Sugarcane        12          0   
2           34         65        62     Black     Cotton         7          9   
3           32         62        34       Red    Tobacco        22          0   
4           28         54        46    Clayey      Paddy        35          0   

   Phosphorous Fertilizer Name  
0            0            Urea  
1           36             DAP  
2           30        14-35-14  
3           20           28-28  
4            0            Urea

In [65]:
fertilizer_data.rename(columns={'Crop Type': "Crop_Type", "Soil Type": "Soil_Type"}, inplace=True)
fertilizer_data.columns

Index(['Temparature', 'Humidity ', 'Moisture', 'Soil_Type', 'Crop_Type',
       'Nitrogen', 'Potassium', 'Phosphorous', 'Fertilizer Name'],
      dtype='object')

In [66]:
from sklearn import preprocessing 
label_encoder = preprocessing.LabelEncoder() 
fertilizer_data['Soil_Type']= label_encoder.fit_transform(fertilizer_data['Soil_Type']) 
fertilizer_data['Crop_Type']= label_encoder.fit_transform(fertilizer_data['Crop_Type']) 

In [67]:
### Independent and Dependent features
X=fertilizer_data.values[:,0:8]
Y=fertilizer_data.values[:,8]

In [68]:
print(X)

[[26 52 38 4 3 37 0 0]
 [29 52 45 2 8 12 0 36]
 [34 65 62 0 1 7 9 30]
 [32 62 34 3 9 22 0 20]
 [28 54 46 1 6 35 0 0]
 [26 52 35 4 0 12 10 13]
 [25 50 64 3 1 9 0 10]
 [33 64 50 2 10 41 0 0]
 [30 60 42 4 4 21 0 18]
 [29 58 33 0 5 9 7 30]
 [27 54 28 1 7 13 0 40]
 [31 62 48 4 3 14 15 12]
 [25 50 65 2 1 36 0 0]
 [32 62 41 1 6 24 0 22]
 [26 52 31 3 2 14 0 41]
 [31 62 49 0 8 10 13 14]
 [33 64 34 1 7 38 0 0]
 [25 50 39 4 0 21 0 19]
 [28 54 65 0 1 39 0 0]
 [29 58 52 2 10 13 0 36]
 [30 60 44 4 4 10 0 9]
 [34 65 53 2 8 12 14 12]
 [35 68 33 3 9 11 0 37]
 [28 54 37 0 4 36 0 0]
 [33 64 39 1 6 13 0 10]
 [26 52 44 4 3 23 0 20]
 [30 60 63 3 1 9 9 29]
 [32 62 30 2 8 38 0 0]
 [37 70 32 0 5 12 0 39]
 [26 52 36 1 7 14 0 13]
 [29 58 40 3 2 24 0 23]
 [30 60 27 2 8 12 0 40]
 [34 65 38 1 6 39 0 0]
 [36 68 38 4 0 7 9 30]
 [26 52 48 2 10 23 0 19]
 [28 54 35 0 4 41 0 0]
 [30 60 61 2 1 8 10 31]
 [37 70 37 1 6 12 0 41]
 [25 50 26 3 2 15 14 11]
 [29 58 34 4 4 15 0 37]
 [27 54 30 1 7 13 0 13]
 [30 60 58 2 8 10 7 32]


In [69]:
print(Y)

['Urea' 'DAP' '14-35-14' '28-28' 'Urea' '17-17-17' '20-20' 'Urea' '28-28'
 '14-35-14' 'DAP' '17-17-17' 'Urea' '28-28' 'DAP' '17-17-17' 'Urea'
 '28-28' 'Urea' 'DAP' '20-20' '17-17-17' 'DAP' 'Urea' '20-20' '28-28'
 '14-35-14' 'Urea' 'DAP' '20-20' '28-28' 'DAP' 'Urea' '14-35-14' '28-28'
 'Urea' '14-35-14' 'DAP' '17-17-17' 'DAP' '20-20' '14-35-14' '28-28'
 'Urea' 'DAP' '14-35-14' '20-20' '28-28' 'Urea' '14-35-14' '28-28' '20-20'
 'Urea' 'DAP' '17-17-17' '28-28' 'Urea' '20-20' '17-17-17' 'DAP' 'Urea'
 '20-20' '28-28' '10-26-26' 'Urea' 'DAP' '20-20' '14-35-14' '10-26-26'
 '20-20' '28-28' 'Urea' '28-28' 'Urea' 'DAP' '14-35-14' '28-28' '20-20'
 '10-26-26' 'DAP' '14-35-14' 'Urea' 'DAP' '20-20' '28-28' '14-35-14'
 '10-26-26' 'Urea' '10-26-26' 'DAP' '14-35-14' '10-26-26' 'Urea'
 '14-35-14' '28-28' '10-26-26' 'Urea' 'DAP' '20-20']


In [70]:
### Train Test Split
from sklearn.model_selection import train_test_split

In [87]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.45,random_state=3)

In [88]:
### Implement Random Forest classifier
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [89]:
## Prediction
y_pred=classifier.predict(X_test)

In [90]:
### Check Accuracy
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)
score*100

97.77777777777777

In [91]:
### Create a Pickle file using serialization 
import pickle
pickle_out = open("fertilizer_predictor.pkl","wb")
pickle.dump(classifier, pickle_out)
pickle_out.close()